version: '3.0'

services:
  main:
    container_name: main
    build:
      context: .
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/modules/node_modules
    ports: 
    - "5000:5000"
    command: npm run start:dev
    depends_on:
      - mysql
    restart: always
  mysql:
    container_name: mysql
    image: mysql:5.7
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: user_schema
      MYSQL_USER: root
      MYSQL_PASSWORD: p1
    ports:
    - "6033:3306"
    volumes:
      - dbdata:/var/lib/mysql
    restart: always
volumes:
  dbdata:

